apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000
  type: NodePort
  selector:
    app: node
    tier: backend
